<?php

/**
 * @file
 * Provides a URL field type that stores external links with optional titles.
 */

/**
 * Implements hook_help().
 */
function url_help($path, $arg) {
  switch ($path) {
    case 'admin/help#url':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The URL module defines a simple link field type for the Field module. Links are external URLs, can have an optional title for each link, and they can be formatted when displayed. See the <a href="@field-help">Field module help page</a> for more information about fields.', array('@field-help' => url('admin/help/field'))) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_field_info().
 */
function url_field_info() {
  $info['url'] = array(
    'label' => t('URL'),
    'description' => t('This field stores URLs with an optional title.'),
    'instance_settings' => array(
      'title_field' => 0,
      'title_fetch' => 0,
    ),
    'default_widget' => 'url_default',
    'default_formatter' => 'url_default',
  );

  return $info;
}

/**
 * Implements hook_field_instance_settings_form().
 */
function url_field_instance_settings_form($field, $instance) {
  $settings = $instance['settings'];

  $form['title_field'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable <em>Title</em> field'),
    '#default_value' => $settings['title_field'],
    '#description' => t('The title attribute is displayed when the link is displayed.'),
  );
  $form['title_fetch'] = array(
    '#type' => 'checkbox',
    '#title' => t('Attempt to fetch the title value from the URL if the <em>Title field</em> is empty.'),
    '#default_value' => $settings['title_fetch'],
  );

  return $form;
}

/**
 * Implements hook_field_presave().
 */
function url_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  $settings = $instance['settings'];

  // If this field is not configured to auto-fetch, stop.
  if (empty($settings['title_fetch'])) {
    return;
  }

  foreach ($items as $delta => $item) {
    if (!empty($item['value']) && empty($item['title'])) {
      // Extract the title from a request to the URL.
      $request = drupal_http_request($item['value']);
      if (empty($request->error) && $request->code == 200 && !empty($request->data)) {
        if (preg_match('!<title>(.*?)</title>!i', $request->data, $matches)) {
          $items[$delta]['title'] = $matches[1];
        }
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 */
function url_field_is_empty($item, $field) {
  return !isset($item['value']) || $item['value'] === '';
}

/**
 * Implements hook_field_widget_info().
 */
function url_field_widget_info() {
  $info['url_default'] = array(
    'label' => t('URL field'),
    'field types' => array('url'),
    'settings' => array('size' => 60),
  );

  return $info;
}

/**
 * Implements hook_field_widget_form().
 */
function url_field_widget_form($form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $settings = $instance['settings'];

  // Display this element in a fieldset if there is only one value.
  if ($field['cardinality'] == 1) {
    $element['#type'] = 'fieldset';
  }

  // URL field value.
  $element['value'] = array(
    '#type' => 'url',
    '#title' => t('URL'),
    '#default_value' => isset($items[$delta]['value']) ? $items[$delta]['value'] : '',
    '#size' => $instance['widget']['settings']['size'],
    '#maxlength' => 2048,
    '#required' => !empty($element['#required']),
    '#prefix' => '<div class="field-value field-value-url">',
    '#suffix' => '</div>',
  );

  // Title field value.
  if (!empty($settings['title_field'])) {
    $element['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#default_value' => isset($items[$delta]['title']) ? $items[$delta]['title'] : '',
      '#maxlength' => 1024,
      '#weight' => 10,
      '#prefix' => '<div class="field-value field-value-title">',
      '#suffix' => '</div>',
    );

    // Add additional styling to make both fields work together visually.
    $element['#attached']['css'][] = drupal_get_path('module', 'url') . '/url.field.css';
  }

  return $element;
}

/**
 * Implements hook_field_prepare_view().
 */
function url_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items) {
  foreach ($entities as $id => $entity) {
    foreach ($items[$id] as $delta => &$item) {
      // Split out the link into the parts required for url(): path and options.
      $options = drupal_parse_url($item['value']);
      $item['path'] = $options['path'];
      $item['options'] = array(
        'query' => $options['query'],
        'fragment' => $options['fragment'],
      );
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function url_field_formatter_info() {
  $info['url_default'] = array(
    'label' => t('Link'),
    'field types' => array('url'),
    'settings' => array(
      'trim_length' => 80,
    ),
  );

  return $info;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function url_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element['trim_length'] = array(
    '#type' => 'number',
    '#title' => t('Trim the link text to certain number of characters'),
    '#description' => t('To leave long link text alone, leave blank.'),
    '#default_value' => $settings['trim_length'],
    '#min' => 1,
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function url_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  if (!empty($settings['trim_length'])) {
    $summary = t('Link text trimmed to @char chars.', array('@char' => $settings['trim_length']));
  }
  else {
    $summary = t('Link text not trimmed.');
  }

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function url_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $intance_settings = $instance['settings'];
  $settings = $display['settings'];

  foreach ($items as $delta => $item) {
    // By default use the full URL as the link title.
    $link_title = $item['value'];

    // If the title field value is available, use it for the link title.
    if (!empty($item['title'])) {
      // Unsanitizied token replacement here because $options['HTML'] is FALSE
      // by default in theme_link().
      $link_title = token_replace($item['title'], array($entity_type => $entity), array('sanitize' => FALSE, 'clear' => TRUE));
    }

    // Trim the link title to the desired length.
    if (!empty($settings['trim_length'])) {
      $link_title = truncate_utf8($link_title, $settings['trim_length'], FALSE, TRUE);
    }

    $element[$delta] = array(
      '#type' => 'link',
      '#title' => $link_title,
      '#href' => $item['path'],
      '#options' => $item['options'],
    );
  }

  return $element;
}
